### ISSUE TITLE
Zapier app not firing

### ISSUE THREAD

**Issue by joseconstela** [pozylon/meteor-docker-auto#2]
Latest Meteor versions on ATOM:
- METEOR@1.10-beta.1
- METEOR@1.10-beta.0
- METEOR@1.9
- ...

Latest on repository: 1.9-beta.3

**Comment by pozylon** [comment]
I just had a look and it's because I've deleted my zeit now team and I would have to reconfigure everything to make this work, if you have some spare time to fix this please take over and fork (see readme for how to set everything up).
